### ISSUE TITLE
Naming Log files before scheduling 

### ISSUE THREAD

**Issue by VellaRo** [jutanke/replik#1]
It would be nice if we could name the Log files because it gets messy if u don't rename /delete them directly afterwards. 
Maybe it could work by just writing the file name in like:

###in .replik/info.json
{
....
..
"stdout_to_file":  "filename", and if it is empty "stdout_to_file":  "", just leave it as default on false.

**Comment by jutanke** [comment]
https://github.com/jutanke/replik/commit/ef3c729bebf08adb8ca915a2c4fbc8520e11f515

You can now specify a user-defined log file name via:
```
replik schedule --script="..." --outfile_name="myoutputfilename"
```
