### ISSUE TITLE
Process kill notification

### ISSUE THREAD

**Issue by anDoer** [jutanke/replik#2]
The tool should provide a proc-file, i.e. /home/user/proc/kill_timeout with values 0/1 indicating whether the currently running containing is going to be killed within the next T minutes. 

This allows to save the current state or terminate the current process in a clean way without data loss.

**Comment by jutanke** [comment]
A secret tag ```run_forever``` is now added that prevents termination for scheduling.

Furthermore, a script under ```docker/killhook.sh``` is added. This script is called 10 seconds BEFORE the ```docker kill``` command is issued, providing some time to the container to gracefully "wrap up".
